# Generated by Django 3.2.7 on 2021-09-11 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(default=0, max_length=50)),
                ('report', models.CharField(default='', max_length=50)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nodeID', models.CharField(max_length=20)),
                ('remark', models.CharField(default=0, max_length=50)),
            ],
            options={
                'db_table': 'Testcase',
            },
        ),
    ]
