# Generated by Django 3.2.7 on 2021-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkingweb', '0002_auto_20210911_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_models',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
