# Generated by Django 3.2.7 on 2021-09-11 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkingweb', '0005_alter_task_models_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_models',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
