# Generated by Django 3.2.7 on 2021-09-11 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pinkingweb', '0006_alter_task_models_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_models',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 15, 55, 26, 175644, tzinfo=utc)),
        ),
    ]
